### ISSUE TITLE
Signal Extension

### ISSUE THREAD

**Issue by dwright-adobe** [Adobe-Marketing-Cloud/aep-sdks-documentation#122]
https://aep-sdks.gitbook.io/docs/using-mobile-extensions/mobile-core/signals/signals-extension-and-rules-engine-integration

What is the "Signals extension"? Did it used to be a separate extension, but is now just part of the Core extension? It's a little confusing to refer to this as an extension since it doesn't appear in Launch as an installable extension.

Also, there are several examples on this page that are completely blank. Can the examples be re-added?

**Comment by praschetan** [comment]
@emdobrin, @kevinlind, @imironchuk FYI

**Comment by emdobrin** [comment]
Hi @dwright-adobe,

Signal is a mobile extension which part of the Mobile Core bundle. It will be downloaded automatically along with the other extensions you selected if you follow the Launch install instructions, and you need to register it with the Mobile SDK as any other extension. 
Since it is part of the Mobile Core extension, once you create a new Mobile property, you can start configuring rules with Signal actions right away and send post backs, collect PII data or open URLs in your app.

Thank you for the feedback, we are working on improving the documentation for Signal and mobile rules in general. I will take a look at those links as well.
Let us know if you have any other questions.

**Emilia Dobrin**
Computer Scientist
[Adobe Experience Cloud](https://www.adobe.com/experience-cloud.html)

**Comment by Robsay** [comment]
I am using the AEP SDK and noticing that the payload on startup is set to GCM for Android apps.

The log entry in Android Studio looks like this:

D/AdobeExperienceSDK: CampaignExtension - processRequest - Campaign Request Queued with url (https://*******-sandbox.adobe.com/rest/head/mobileAppV5/@YbyiVrJB5VoiREkHe_JyohyYvxOREuJjngnWTaKlelvapqcTcnlbk4POgDOUoTLnzkRMQ4Sm6uFh_EIEcdSylkc7eKZXJdHS5jce6WULYr7U6lCyWDfis50xtplhd6mq5mhWbA/subscriptions/84468840125982782508671000597616434081) and body ({"marketingCloudId":"84468840125982782508671000597616434081","pushPlatform":"gcm"})

 When creating a push event transactional message in Adobe Campaign(ACS) the delivery connected to it, automatically creates 3 variants, iOS,GCM and FCM and the only variant working for receiving Android messages is the GCM variant because of the default value. But when using Push notification from within a workflow in ACS, then you have to use FCM. This is incongruent behaviour. Also: "On April 10, 2018, Google deprecated GCM. The GCM server and client APIs were removed on May 29, 2019. Migrate GCM apps to Firebase Cloud Messaging (FCM), which inherits the reliable and scalable GCM infrastructure, plus many new features. See the migration guide to learn more."https://developers.google.com/cloud-messaging/faq

Can we make sure that the payload no longer defaults to GCM? And we should not have  to hardcode the value for the pushPlatform postbackin Launch because it would put a limit  in creating applications across platforms.

**Comment by rymorale** [comment]
Hi @Robsay,

I have opened a bug to look into updating the push platform value in the Campaign payload. I noticed that you also posted a similar question at https://experienceleaguecommunities.adobe.com/t5/Adobe-Experience-Platform-SDKs/AEP-SDK-How-to-change-PushPlatform-default-value-GCM/qaq-p/350481. We will update the experience league forum post going forward with any future updates because this current github issue appears to be unrelated to Campaign.

Thanks,
Ryan Morales
Mobile Engineer
[Adobe Experience Cloud](https://www.adobe.com/experience-cloud.html)

**Comment by Robsay** [comment]
Hi @rymorale 

Thank you for taking the time to look into this. It is true I posted in the Adobe forum as well. I am having serious difficulties reaching the right audience for my questions regarding AEP SDK and Experience Cloud related issues , I am a member of several Slack channels, access to Neolane Support, Adobe Customer Support and follow the progress on Github for AEP, so I use the shotgun method to try and get hold of someone with the right connections and actual knowledge :) 

Happy new year and thanks
Robert Ayzma
Solution Architect
Isobar Denmark
