### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by acharron** [Adobe-Marketing-Cloud/aep-sdks-documentation#128]
## Problem

Since the start of the Launch platform and the new SDK, the documentation for the mobile SDKs changed from https://marketing.adobe.com/resources/help/en_US/mobile/ios to https://aep-sdks.gitbook.io/docs/
(There's apparently been more migrations, but I didn't keep track). All of this seems to reflect the drop of support for DTM and the 4.x SDKs (see https://medium.com/launch-by-adobe/dtm-plans-for-a-sunset-3c6aab003a6f for DTM. I actually don't know the EOL planned for the 4.x SDKs)

However, the documentation here doesn't seem to support internationalisation like the old docs used to. Is there any ETA for a translation support?

Thanks!

### Drop of support announced in Sept 2018

I'm currently working with a Japanese team, and the docs for the Analytics SDK (4.x) tells us that the new Launch platform and SDKs are available and invites us to switch, but no resources in Japanese are available in the links provided.

> 重要：2018 年 9 月に、SDK の新しいメジャーバージョンをリリースしました。(........)

https://marketing.adobe.com/resources/help/ja_JP/mobile/ios/analytics_main.html

### Comparison 

For example, the "Analytics -> Product variable" page, available in JP for 4.x : https://marketing.adobe.com/resources/help/ja_JP/mobile/ios/products.html

But only in EN for the new version : https://aep-sdks.gitbook.io/docs/using-mobile-extensions/adobe-analytics/product-variable

(Funnily enough, the 4.x docs in Japanese provides a "Switch language" in the bottom right, but switching back to EN offers a blank page. The old documentation seems to have moved. Although that's an entirely different problem)

**Comment by rekrishn** [comment]
@acharron, 

Currently there is no localization planned with the AEP SDK documentation. This is because the doc tool we are currently using (GitBook) does not support translations. 

The v4 SDK documentation has been migrated from "marketing.adobe.com" to "docs.adobe.com". For example here is the Android SDK guide: https://docs.adobe.com/content/help/en/mobile-services/android/overview.html. As a result, the "marketing.adobe.com" links no longer work. 

Please update your book marks to the following:

- Mobile Services user's guide: https://docs.adobe.com/content/help/en/mobile-services/using/home.html

- Android SDK guide: https://docs.adobe.com/content/help/en/mobile-services/android/overview.html

- iOS SDK guide: https://docs.adobe.com/content/help/en/mobile-services/ios/overview.html

Localization is planned for this content in the future. Also, the AEP SDK docs will be migrated to "docs.adobe.com" later this year or early next year.
